dist: trusty
script: script/ci
sudo: required
os: linux
lang: ruby

#

rvm:
  - 2.3.0

#

env:
  global:
    - DOCKER_EMAIL=jekyllbot@jekyllrb.com
    - DOCKER_USERNAME=jekyllbot
    - secure: "\
        Ch58f9OmZoF7b6j2o7WKzw9EZ+Mah69sZnM6YFjWcPw3RDBzM7DFpu8zaB0n2MiXUc+fiCEQ\
        MuW/bjWO8xhO2dp2HcDkTn4vOvO+gKBqhjTN2abLb2fq13LDQJ3DwxPpqDnV8K5Kgd2qj7W1\
        D3o1rY4zdECw9Wi9LaiUeQu43lc=\
      "
  matrix:
    - DOCKER_REPO=jekyll
    - DOCKER_REPO=builder
